{% set name = "omnisci-pytools" %}
{% set version = "3.0.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/j/jupyterlab-omnisci/jupyterlab-omnisci-{{ version }}.tar.gz
  sha256: de83d62f4b2738d53d9d5fdab463d99195f3cd1d2a1700713cea307926e858dc

build:
  number: 1
  noarch: python

requirements:
  host:
    - python >=3
    - pip
    - nodejs
  run:
    - python >=3
    - nodejs
    - jupyterlab
    - pymapd
    - ibis-framework
    - ipython
    - ipywidgets
    - vdom
    - altair
    - vega_datasets
    - pyyaml

test:
  imports:
    - jupyterlab_omnisci

about:
  home: https://github.com/Quansight/jupyterlab-omnisci
  license: Apache-2.0
  license_family: Apache
  license_file: LICENSE
  summary: 'JupyterLab - Omnisci integration'

  description: |
    'JupyterLab - Omnisci integration'
  dev_url: https://github.com/Quansight/jupyterlab-omnisci

extra:
  recipe-maintainers:
    - andrewseidl
    - mikehinchey
    - jp-harvey
    - scopatz
    - xmnlab
